/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, clang++ 17.0.6 -fPIC -O3) */

module FullAdder(a_i, b_i, cin_i, sum_o, cout_o);
  wire _0_;
  wire _1_;
  wire _2_;
  input a_i;
  wire a_i;
  input b_i;
  wire b_i;
  input cin_i;
  wire cin_i;
  output cout_o;
  wire cout_o;
  output sum_o;
  wire sum_o;
  sky130_fd_sc_hd__o21ai_2 _3_ (
    .A1(_0_),
    .A2(_2_),
    .B1(_1_),
    .Y(cout_o)
  );
  sky130_fd_sc_hd__inv_2 _4_ (
    .A(cin_i),
    .Y(_0_)
  );
  sky130_fd_sc_hd__nand2_2 _5_ (
    .A(b_i),
    .B(a_i),
    .Y(_1_)
  );
  sky130_fd_sc_hd__xnor2_2 _6_ (
    .A(b_i),
    .B(a_i),
    .Y(_2_)
  );
  sky130_fd_sc_hd__xnor2_2 _7_ (
    .A(cin_i),
    .B(_2_),
    .Y(sum_o)
  );
endmodule
