/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, clang++ 17.0.6 -fPIC -O3) */

(* top =  1  *)
(* src = "FullAdder.v:11.1-29.10" *)
module FullAdder(a_i, b_i, cin_i, sum_o, cout_o);
  (* src = "FullAdder.v:27.22-27.31" *)
  wire _0_;
  (* src = "FullAdder.v:27.36-27.50" *)
  wire _1_;
  (* src = "FullAdder.v:12.17-12.20" *)
  input a_i;
  wire a_i;
  (* src = "FullAdder.v:23.10-23.16" *)
  wire ab_xor;
  (* src = "FullAdder.v:13.17-13.20" *)
  input b_i;
  wire b_i;
  (* src = "FullAdder.v:14.17-14.22" *)
  input cin_i;
  wire cin_i;
  (* src = "FullAdder.v:16.17-16.23" *)
  output cout_o;
  wire cout_o;
  (* src = "FullAdder.v:15.17-15.22" *)
  output sum_o;
  wire sum_o;
  assign ab_xor = a_i ^(* src = "FullAdder.v:25.21-25.30" *)  b_i;
  assign sum_o = ab_xor ^(* src = "FullAdder.v:26.21-26.35" *)  cin_i;
  assign _0_ = a_i &(* src = "FullAdder.v:27.22-27.31" *)  b_i;
  assign _1_ = cin_i &(* src = "FullAdder.v:27.36-27.50" *)  ab_xor;
  assign cout_o = _0_ |(* src = "FullAdder.v:27.21-27.51" *)  _1_;
endmodule
